// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr0t3DanY4h0V9jADvTUx8ku9e9kruwH4',
    appId: '1:586786529692:web:0e61e2838d149d2b58e859',
    messagingSenderId: '586786529692',
    projectId: 'getx-ea44b',
    authDomain: 'getx-ea44b.firebaseapp.com',
    storageBucket: 'getx-ea44b.appspot.com',
    measurementId: 'G-9JV0PSVBW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz0xyhBChOF2dNYOfialtBH-cKubw4hwA',
    appId: '1:586786529692:android:87c61b797d98d2cf58e859',
    messagingSenderId: '586786529692',
    projectId: 'getx-ea44b',
    storageBucket: 'getx-ea44b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5oU2D1tfyfw90vTdhOAmrDR98LCSrMBc',
    appId: '1:586786529692:ios:1ad76d34959d614358e859',
    messagingSenderId: '586786529692',
    projectId: 'getx-ea44b',
    storageBucket: 'getx-ea44b.appspot.com',
    iosClientId: '586786529692-vhgc4ur13od6cc7tdhpd4uj0in93479h.apps.googleusercontent.com',
    iosBundleId: 'com.example.authWithGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5oU2D1tfyfw90vTdhOAmrDR98LCSrMBc',
    appId: '1:586786529692:ios:1ad76d34959d614358e859',
    messagingSenderId: '586786529692',
    projectId: 'getx-ea44b',
    storageBucket: 'getx-ea44b.appspot.com',
    iosClientId: '586786529692-vhgc4ur13od6cc7tdhpd4uj0in93479h.apps.googleusercontent.com',
    iosBundleId: 'com.example.authWithGet',
  );
}
